name: Build SL3000

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL https://is.gd/depends_ubuntu_2204)
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: Clone
        run: git clone https://github.com/openwrt/openwrt -b openwrt-24.10 openwrt

      - name: Feed
        run: cd openwrt && ./scripts/feeds update -a && ./scripts/feeds install -a

      - name: Inject
        run: |
          chmod +x diy-part2.sh
          cd openwrt
          $GITHUB_WORKSPACE/diy-part2.sh
          # 执行强制对齐
          make defconfig

      - name: Toolchain
        run: |
          cd openwrt
          # 物理构建 ARM64 环境，必须先执行
          make tools/install -j$(nproc)
          make toolchain/install -j$(nproc)

      - name: U-Boot
        run: |
          cd openwrt
          # 指定物理路径编译
          make package/boot/uboot-mediatek/compile V=s -j1

      - name: Firmware
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: SL3000-Firmware
          path: openwrt/bin/targets/mediatek/mt7981/*.bin
